#!/usr/bin/env bash

for f in $*
do
    echo ''
    f2=${f%.*}.txt
    echo process $f to $f2
    if [ -f "$f2" ];then
        echo $f2 already exists
    else
        echo cargo run -- --in $f --out $f2 --parallel-count 30
        cargo run -- --in $f --out $f2 --parallel-count 30
    fi
done
